from __future__ import annotations

import os
import time
import uuid
from datetime import datetime, timedelta, timezone, date
from pathlib import Path
from typing import Optional

from fastapi import Depends, FastAPI, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field, model_validator

from app.fr24_client import fetch_flight_summary_full
from app.mapping import find_mappings_for_msn
from app.report_builder import build_normalized_rows, create_xlsx_report
from app.security import require_api_key, sign_download, validate_download_signature

app = FastAPI(title="FR24 GPT Report Backend", version="1.0.0")


class ReportRequest(BaseModel):
    msn: Optional[str] = Field(default=None, description="Manufacturer serial number. Backend maps this to registration.")
    registration: Optional[str] = Field(default=None, description="Aircraft registration, e.g. EI-EIN.")
    from_date: Optional[date] = Field(default=None, description="Start date, yyyy-mm-dd.")
    to_date: Optional[date] = Field(default=None, description="End date, yyyy-mm-dd.")
    days: int = Field(default=20, ge=1, le=370, description="Lookback days when dates are omitted.")

    @model_validator(mode="after")
    def validate_identity(self):
        if not self.msn and not self.registration:
            raise ValueError("Provide either msn or registration")
        return self


class ReportResponse(BaseModel):
    success: bool
    report_id: str
    msn: str | None
    registrations: list[str]
    from_date: str
    to_date: str
    row_count: int
    total_flight_hours: float
    download_url: str
    notes: list[str]


def resolve_date_range(req: ReportRequest) -> tuple[datetime, datetime]:
    today = datetime.now(timezone.utc).date()
    end_d = req.to_date or today
    start_d = req.from_date or (end_d - timedelta(days=req.days))

    if start_d >= end_d:
        raise HTTPException(status_code=400, detail="from_date must be before to_date")

    max_days = int(os.environ.get("MAX_REPORT_DAYS", "370"))
    if (end_d - start_d).days > max_days:
        raise HTTPException(status_code=400, detail=f"Report range exceeds MAX_REPORT_DAYS={max_days}")

    start_dt = datetime.combine(start_d, datetime.min.time(), tzinfo=timezone.utc)
    end_dt = datetime.combine(end_d, datetime.max.time(), tzinfo=timezone.utc)
    return start_dt, end_dt


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/reports", response_model=ReportResponse, dependencies=[Depends(require_api_key)])
def create_report(req: ReportRequest) -> ReportResponse:
    start_dt, end_dt = resolve_date_range(req)

    mappings_notes: list[str] = []
    registrations: list[str]
    if req.registration:
        registrations = [req.registration.strip().upper()]
    else:
        mappings = find_mappings_for_msn(req.msn or "", start_dt.date(), end_dt.date())
        registrations = sorted({m.registration for m in mappings if m.registration})
        mappings_notes = [
            f"MSN {m.msn} mapped to {m.registration} effective {m.effective_from or 'open'} to {m.effective_to or 'open'}."
            for m in mappings
        ]

    raw_items = []
    for reg in registrations:
        raw_items.extend(fetch_flight_summary_full(reg, start_dt, end_dt))

    normalized = build_normalized_rows(raw_items)
    normalized.sort(key=lambda row: (str(row.get("Date") or ""), str(row.get("ATD") or "")))

    report_id = uuid.uuid4().hex[:12]
    report_dir = Path(os.environ.get("REPORT_DIR", "reports"))
    report_dir.mkdir(parents=True, exist_ok=True)
    file_path = report_dir / f"fr24_report_{report_id}.xlsx"

    create_xlsx_report(
        file_path,
        msn=req.msn.strip().upper() if req.msn else None,
        registrations=registrations,
        start_date=start_dt.date(),
        end_date=end_dt.date(),
        rows=normalized,
        mapping_notes=mappings_notes,
    )

    expires = int(time.time()) + 3600
    signature = sign_download(report_id, expires)
    base_url = os.environ.get("BASE_URL", "http://localhost:8000").rstrip("/")
    download_url = f"{base_url}/reports/{report_id}/download?expires={expires}&signature={signature}"

    total_hours = sum((row.get("Flight Time") or 0) * 24 for row in normalized)

    return ReportResponse(
        success=True,
        report_id=report_id,
        msn=req.msn.strip().upper() if req.msn else None,
        registrations=registrations,
        from_date=start_dt.date().isoformat(),
        to_date=end_dt.date().isoformat(),
        row_count=len(normalized),
        total_flight_hours=round(total_hours, 1),
        download_url=download_url,
        notes=mappings_notes + [
            "Excel file is generated by the backend, not by Google Sheets.",
            "Download link expires in 1 hour.",
        ],
    )


@app.get("/reports/{report_id}/download")
def download_report(report_id: str, _: None = Depends(validate_download_signature)) -> FileResponse:
    report_dir = Path(os.environ.get("REPORT_DIR", "reports"))
    file_path = report_dir / f"fr24_report_{report_id}.xlsx"
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Report not found")
    return FileResponse(
        path=str(file_path),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        filename=file_path.name,
    )
